### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Themis1** [otahontas/sointutietokanta#1]
Zip-tiedosto ladattu 19.8. klo 22.30

## Yleistä

Sointutietokannassa on tarkoitus ylläpitää tietoa kappaleista ja soinnuista sekä linkittää nämä kaksi toisiinsa, eli mitä sointuja missäkin kappaleissa käytetään. Lisäksi tarkoituksena on, että käyttäjä voi merkitä lempikappaleitaan sekä lisätä uusia sointuja ja kappaleita. Tarkoitus on myös, että käyttäjinä on sekä peruskäyttäjiä että ylläpitäjiä, ja ylläpitäjillä olisi myös oikeus poistaa ja muokata sointuja. Tietokantakaaviota katsoen on tässä tarkoitus toteuttaa melko kunnianhimoinen tietokanta.

## Toiminnallisuudet tällä hetkellä

* Tietokantaan voi luoda uuden käyttäjän ja kirjautua tällä käyttäjällä, sekä kirjautua ulos.
* Tietokantaan voi lisätä uusia kappaleita.
* Tietokantaan voi lisätä uusia sointuja.
* Sointuja voi tarkastella yksitellen. Sointu avautuu samassa ikkunassa, jolloin toinen mahdollisesti auki oleva sointu sulkeutuu.
* Tietokanta hakee nuotteja valmiiksi tallennetusta listasta.

## Testaus

* Dokumentaatiossa annettu käyttäjätunnus ei toimi. Epäselvää on myös, olisiko tämä ollut admin-tunnus. Admin-toiminnallisuuksia ei siis pääse testaamaan. Toisaalta näitä ei myös taida olla toteutettu vielä.
* Kaikki näkyvät toiminnallisuudet toimivat moitteetta sekä paikallisesti että Herokussa.

## Koodi

* Koodi on kaiken kaikkeaan selkeää ja lähes kaikkialla on kirjoitettu kommentilla luokan/metodin toiminta.
* Ulkoasulle on käytetty paljon koodia. En näitä sen tarkemmin käy läpi, sillä ulkoasu on looginen ja yhdenmukainen. Koodi tältä osin on siis oikein toimiva.
* Kansiorakenne on selkeä. Eri taulut ja metodit ovat loogisesti jaoteltu.
* Koodiin on toteutettu kaksi abstraktia luokkaa, joiden avulla muihin luokkiin voi lisätä joko id:n tai päiväyksen (tai molemmat). Tämä on kätevää toteuttaa näin erikseen, jos kaikkiin muihin tauluihin ei ole tarvetta lisätä esim. päiväystä.
* Koodiin on toteutettu kaksi liitetaulua: notes ja linktables. Notes ei taida varsinaisesti olla liitetaulu, vaan se sisältää listan nuoteista, joita voi käyttää soinnuissa.
* Chords-taulu käyttää tallennettua notes-listaa, jonka toiminta on minulle hieman epäselvä. Testatessa se toimii, joten se on toteutettu oikein. En löydä varsinaista linkkiä notes-tiedostoon mistään. Tämä on omiin silmiini melko vaikuttavaa, joten hienoa, että se toimii!
* Toimintoja on jaoteltu sen mukaan pitääkö käyttäjän olla kirjautuneena. Tämä toimii kuten pitääkin.
* Koodissa on paljon riippuvuuksia (relationship). Ne vaikuttaisivat olevan toteutettu oikein, joka on melko vaikuttavaa, sillä näitä liitoksia on tosiaan paljon.

## Puutteita / kehitettävää

* Tietokannasta ei vielä pysty poistamaan mitään.
* Tietokannassa ei vielä pysty muokkaamaan mitään.
* Adminille ei ole tehty erillisiä toimintoja. Tämän voisi toteuttaa luomalla Role-luokka auth/models.py-tiedoon. Sitten myös toimintoihin voisi edellyttää kirjautumisen lisäksi tiettyä roolia.
* Monet käyttötapauksista ovat vielä toteuttamatta. Tämä tosin on huomioitu TODO-listalla.
* Monen suhde moneen -taulu puuttuu.
* Tietokantakaaviosta lähes kaikki on toteutettu. Lempikappaleen valinta, laulun käyttämien sointujen valinta sekä käyttäjän rooli puuttuvat vielä.

## Muuta

* Ulkoasu on toimiva ja miellyttävä. Jos jää aikaa, olisi kiva lisätä sivulle vähän grafiikkaa tms. Ulosanti on nyt vähän valju.
* Flash-viesti mm. kirjauduttaessa sisään ja ulos on kiva lisä.
* Vaikka varsinaisia toiminnallisuuksia on vasta vähän, on koodi erittäin vaikuttavaa ja taustalle on rakennettu paljon liitoksia.
* Keep up the good work!

**Comment by otahontas** [comment]
Kiitos kommenteista ja tsempeistä, oli hyvä palaute! Olin näköjään unohtanut luoda testitunnarit uusiksi Postgresin alustamisen jälkeen, mutta hyvä, että sait silti testailtua :D
